{
 "title": "Takeoff Logs",
 "tags": [ "takeoff" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": "takeoff,takeoff-stage,takeoff-dev"
   }
  ]
 },
 "panels": [
  {
   "title": "Controller logs",
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "{app=~\".*takeoff-controller.*\", namespace=\"$namespace\"} !~ `status`"
    }
   ]
  },
  {
   "title": "Embed Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {
     "expr": "{app=~\".*takeoff-embed.*\", namespace=\"$namespace\"}"
    }
   ]
  },
  {
   "title": "Generate Logs",
   "type": "logs",
   "gridPos": { "h": 16, "w": 24, "x": 0, "y": 31 },
   "targets": [
    {
     "expr": "{app=~\".*takeoff-generate.*\", namespace=\"$namespace\"}"
    }
   ]
  }
 ]
}